### ISSUE TITLE
Add topic hacktoberfest

### ISSUE THREAD

**Issue by AbhishekMaira10** [abhisheknaiidu/javascript30#27]
There has been an update regarding hacktoberfest to reduce spam. It only accepts valid PR's
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
The PR is merged OR
The PR is labelled as hacktoberfest-accepted by a maintainer OR
The PR has been approved
)

find out more at - https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by abhisheknaiidu** [comment]
Hey @AbhishekMaira10 thanks for informing, but I think we are fine, right? as I'm approving all the PR's before it's getting merged, or am I missing anythin?

**Comment by AbhishekMaira10** [comment]
yes approving is fine when evaluating the pull request but I am saying 'hacktoberfest' topic has to be added in the about section of the repository.

**Comment by abhisheknaiidu** [comment]
@AbhishekMaira10 Fine, i'll do it then! Thanks.
